apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: Vidal
type: Opaque
data:
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpucGdfVkx3MTRkS2JubEl4QGVwLXdpdGhlcmVkLWJpcmQtYWNhOGVsYmQtcG9vbGVyLnNhLWVhc3QtMS5hd3MubmVvbi50ZWNoL2FwaWFpP3NzbG1vZGU9cmVxdWlyZSZjaGFubmVsX2JpbmRpbmc9cmVxdWlyZQ==
  DATABASE_USERNAME: bmVvbmRiX293bmVy
  DATABASE_PASSWORD: bnBnX1ZMdzE0ZEtibmxJeA==
  YOUTUBE_API_URL: aHR0cHM6Ly95b3V0dWJlLW1wMzYucC5yYXBpZGFwaS5jb20=
  YOUTUBE_API_HOST: eW91dHViZS1tcDM2LnAucmFwaWRhcGkuY29t
  YOUTUBE_API_KEY: MTFkNWE1OWE3MG1zaDkyOGE2YjUxODk1ZTcwMnAxMmFiODdqc243YjRmMjRjNjI4YmE=
  INSTAGRAM_API_URL: aHR0cHM6Ly9pbnN0YWdyYW0xMjAucC5yYXBpZGFwaS5jb20=
  INSTAGRAM_API_HOST: aW5zdGFncmFtMTIwLnAucmFwaWRhcGkuY29t
  INSTAGRAM_API_KEY: MTFkNWE1OWE3MG1zaDkyOGE2YjUxODk1ZTcwMnAxMmFiODdqc243YjRmMjRjNjI4YmE=


# Comandos para convertir a Base64 y decodificar | https://www.convertstring.com/es/EncodeDecode/Base64Encode
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode

# echo -n "r2dbc:postgresql://ep-rough-dream-a5jgv01u-pooler.us-east-2.aws.neon.tech/sql?sslmode=require" | base64
# echo -n "db_owner" | base64
# echo -n "CTtqXi6G2NFx" | base64

# echo -n "https://age-detector.p.rapidapi.com" | base64
# echo -n "age-detector.p.rapidapi.com" | base64
# echo -n "3054dca294msh311fcc16893ce74p17ef24jsncbd8ead6ed76" | base64