# kubectl apply -f 4-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: age-detector
  namespace: Vidal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: age-detector
  template:
    metadata:
      labels:
        app: age-detector
    spec:
      containers:
      - name: age-detector
        image: vidalluyo0/api-ai:v1   # Reemplaza con tu imagen Docker
        imagePullPolicy: IfNotPresent        # Evitar traer siempre la última versión si hay una actual
        envFrom:
        - secretRef:
            name: credentials  # Esto cargará todos los valores como variables de entorno